//Wはラッパー
import React from 'react';
import HeaderImage from '@/atoms/layout/HeaderImage';
import Head from 'next/head';
import styled from 'styled-components';
import Header from '@/organisms/layout/Header';
import Grid, { GridSpacing } from '@mui/material/Grid';
import WContainer from '@/atoms/layout/WContainer';
import UserHeader from '@/components/organisms/user/Header';

type Props = {
  title: string;
  children: React.ReactNode;
  user_image_src: string;
};

function MainLayout(props: Props): JSX.Element {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <Grid container spacing={3}>
        <Grid item xs={12}>
          <HeaderImage />
        </Grid>
        <WContainer>
          <Grid container>
            <Grid item xs={12}>
              <UserHeader user_image_src={props.user_image_src} />
            </Grid>
            <Grid item xs={12}>
              {props.children}
            </Grid>
          </Grid>
        </WContainer>
      </Grid>
    </>
  );
}

export default MainLayout;
