import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import WAvatar from '@/components/atoms/WAvatar';
import MainLayout from '@/components/templates/MainLayout';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
   
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

        <MainLayout>
            <WAvatar/>
        </MainLayout>
    </div>
  );
};

export default Home;
