import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import WAvatar from '@/components/atoms/avatar/WAvatar';
import MainLayout from '@/components/templates/MainLayout';

const Home: NextPage = () => {
  return (
    <MainLayout>
      <Head>
        <title>MojaPortfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </MainLayout>
  );
};

export default Home;
